server:
  port: 9000
  context-path: /beerhouse

spring:
  application:
    name: cervejaria-renan

  h2:
    console:
    enabled: true
    path: /h2

  datasource:
    url: jdbc:h2:file:./data/exemplo
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
    show-sql: true
