server:
  port: 9000
  context-path: /beerhouse

spring:
  application:
    name: cervejaria-renan

  datasource:
    url: jdbc:mysql://localhost:3306/craft_beer?useSSL=false&useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: masterkey

  jpa:
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate.ddl-auto: update
    show-sql: false
    hibernate:
    jdbc: time_zone = TimeZone
